# [_The Ethnographer and the Algorithm: Beyond the Black Box_](./assets/ethnoalgo.pdf){target="_blank"}, Angèle Christin. {-} 

- Three strategies for algorithmic ethnography: 
  - Algorithmic refraction (reconfigurations that come from socio-technical interactions)
  - Algorithmic comparison (similarity and difference approach to identify unique features)
  - Algorithmic triangulation (using algorithms to get rich qualitative data, address saturation, positionality, and disengagement)
- Algorithms conventionally thought to be opaque "black boxes" (understood in terms of input and output, without knowledge of internal workings)
  - Opaque because of: 
    - intentional secrecy (companies keep secrets / intellectual property)
    - technical illiteracy 
    - unintelligible evolution 
    - sheer size
- Others say algorithms not fit in neatly technical boxes
  - They do algorithmic audits, cultural and historical critiques, and ethnography as methodological strategies
- Ethnography aims to understand the representations, practices and cultures of the people being analyzed
- "Technologies-in-use" paradigm (studies practices and representations of users)
- Black boxing can be analyzed as an artefact of scientific and technological legitimacy 
  - Latour -- “scientific and technical work is made invisible by its own success. When a machine runs efficiently, when a matter of fact is settled, one need to focus only on its inputs and outputs and not on its internal complexity. Thus, paradoxically, the more science and technology succeed, the more opaque and obscure they become” 
  - Thus, focus on substitutions and associations within assemblages of humans and non-humans
  - Enrollment key in this framework: analyze the dynamics of association,
translation, and entanglement that take place whenever humans and non-humans
interact
  - Intressment a form of incentivization, part of enrollment
- From Malcolm, on dialetical relationship between journalist and criminal: “Every journalist who is not too stupid or full of himself to notice what is going on knows that what he does is morally indefensible. He is a kind of confidence man, preying on people’s vanity, ignorance, or loneliness, gaining their trust and betraying them without remorse”
  - does not account for the collective and institutional dynamics
shaping the relationship between ethnographers and their informants (?)
  - central value of contemporary ethnographic research is to try to make explicit as much of the research process as possible for the ethnographic community as a whole
- Humans in the loop, evolving forms of social responsibility within automated systems 