# [_Simulation and Similarity:Using Models to Understand the World_](./assets/simandsim.pdf){target="_blank"}, Michael Weisberg. {-} 

- Models are indirect study of real-world systems, different from other forms of representation and analysis, interpreted structures 
- Three types of modelling: mathematical, computational, concrete 
  - concrete are physical objects whose physical properties can potentially stand in representational relationships with real-world phenomena 
  - mathematical are abstract structures whose properties can potentially stand in relations to mathematical representations of phenomena 
    - can't be assessed or measured directly, so what we learn comes from manipulating the equations that describe it 
    - either set-theoretic predicates or sets of trajectories in state space
  - computational models are sets of procedures that can potentially stand in relation to computational description of the behavior of a system 
- Doesn't take model organisms, verbal models, and idealized exemplars because they fit into above taxonomy 
  - Is taxonomy sociological, ontological, or epistemic 
- Models not always veredical (do not always truthfully describe all aspects of their targets)
- Feyerabend's dictum: "Anything goes in science" 
- Agent-based model means that each individual is explicitly represented 
- Model descriptors are the words, equations, and pictures that describe a model
  - Giere said model descriptions were the set of statements that define a model
- Construals provide interpretation for the model's structure (assignment, scope, fidelity criteria)
  - two kinds of fidelity criteria: dynamic and representational 
    - dynamic tells us how close the output of the model must be to the output of real world phenomenon 
    - representational gives us standards for evaluating how well the structure of the model maps onto the target system of interest 
- Fictionalist accounts vs. Maths accounts 
- Idealization is the intentional introduction of distortion into scientific representations 
- Modelling as theorhetical practice 